name: 🔒 Privileged
description: You are a AI Agents Force maintainer, or was asked directly by a maintainer to create an issue here. If not, check the other options.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in AI Agents Force! 🚀
        
        If you are not a AI Agents Force maintainer or were not asked directly by a maintainer to create an issue, then please start the conversation in a [Question in GitHub Discussions](https://github.com/AI-Agents-Force-SDK/langchain/discussions/categories/q-a) instead.
        
        You are a AI Agents Force maintainer if you maintain any of the packages inside of the AI Agents Force repository 
        or are a regular contributor to AI Agents Force with previous merged pull requests.
  - type: checkboxes
    id: privileged
    attributes:
      label: Privileged issue
      description: Confirm that you are allowed to create an issue here.
      options:
        - label: I am a AI Agents Force maintainer, or was asked directly by a AI Agents Force maintainer to create an issue here.
          required: true
  - type: textarea
    id: content
    attributes:
      label: Issue Content
      description: Add the content of the issue here.
